### ISSUE TITLE
version 1.4.3 not present in maven central

### ISSUE THREAD

**Issue by paulux84** [filosganga/geogson#61]
As i think you know the last version isn't present in [central maven repo](https://search.maven.org/#search%7Cga%7C1%7Cfilosganga)

**Comment by carlos-mg89** [comment]
This is still an issue. Would there be anyone who knows how to fix this or is just the author of this repo who can do it?

**Comment by filosganga** [comment]
A new version has been released to maven central, sorry about massive delay
